{% set name = "serverfiles" %}
{% set version = "0.3.0" %}
{% set sha256 = "ce38e1dc3518a16b2490f7b84b4ce829f2d6685596c1a3f0fdedbe06d13685ec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests >=2.11.1

test:
  imports:
    - serverfiles

about:
  home: https://github.com/biolab/serverfiles/
  license: GPL-3
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'An utility that accesses files on a HTTP server and stores them locally for reuse'

  doc_url: https://serverfiles.readthedocs.io/en/latest/
  dev_url: https://github.com/biolab/serverfiles/

extra:
  recipe-maintainers:
    - astaric
