travis:
  secure:
    BINSTAR_TOKEN: CMK1PJvs7+OD2n0XvVTvKawrel9LIsUbCqXayaZOvSfvN4ZVxGXJ4UrjRJuw5An4viRH2IdUWqmemJQRMxXpuQfSPONasQ7MZOmEp83M7yU19KOCmbTMJZTIEv8meQvFRRFssTHBY3c/VBxKMw3/qEypdwliWv+tSfqY9fgs5X3PoIl5GJqmcgzegsyA58bfqzmjgv8qTrepklTjj1XEp+EEuqTpmoEMIAh0Q/yGMASI+cXB5YNeo/MBx1b2D7rRPRSYAuPDkSIU+tewiLN4iguj9UCp2PbZXj+uT8fZPY6aIKtSYJH4BbGKEzu9zjIZp8a7f3SwBn7ePet5cB6BPkpvunlFMKkjzLEIVCjlwFyfbvYv4xVGnm//VuRyei3QcJrmz00dHYIT8TJrkecU8zryEq0qrep4T/R6O6HQUjBQXfFsnKum4ZWJtkUtRGtgir1gh7fy0YfakjvrTnDh81CNx9gsQ0ZYaLhnQw4tsVldnIW6dBocJkXlE+Ggb2OjJhMnkc4Gk8L2YUzAnljhASGRf156JFVcMovYfU52vbyVvnWvzxo2VvXMFkr1Rc5gI7s6Vi3c9Hw1WTSPmKxiX51x5bnRjM7ibm5IZ0JbF/Vc57j+KYgrYt290fdzyNbl+fN+4hnxZFom7bdw2Cv2LApL45f7uaPpWTSIiIIiI18=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
